### ISSUE TITLE
Help Property Support

### ISSUE THREAD

**Issue by brian-ruf** [metaschema-framework/metaschema-java#131]
### User Story

As a user of the metaschema-java tool, I want to consume metaschema definitions that includes help properties. As the metaschema-java tool identifies issues where the content does not satisfy metaschema-defined constraints, I want the tool to include the help property values in the SARIF output. The tool should not require the help properties and only include them in SARIF output if they are present in the metaschema constraint. 

This issue supports the [draft FedRAMP ADR 9](https://github.com/aj-stein-gsa/fedramp-automation/blob/720-docs-adr-metapath-sarif-help-url/documents/adr/0009-constraint-based-help-docs.md) in GSA/fedramp-automation#735.

### Goals

The metaschema-java tool:
- recognizes and honors help properties in Metaschema constraints
- when a help property is present, populates the help property values in the SARIF output for any content issues associated with the constraint  

### Acceptance Criteria

- [ ] Help property syntax is recognized by the metaschema-java tool
- [ ] Help property values appear in the SARIF output when present in a defined constraint that is not satisfied by evaluated content
- [ ] All website and readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by brian-ruf** [comment]
Per the FedRAMP Automation Team's 2024-09-26 discussion, the following properties will be used in FedRAMP constraint definitions and must be recognized by the above capability:
- `//constraint/prop[@name='help-text'][@namespace='https://json.schemastore.org/sarif/2.1.0']`
- `//constraint/prop[@name='help-url'][@namespace='https://json.schemastore.org/sarif/2.1.0']`

The FedRAMP Automation Team intends to use plan text and markdown text in the `help-text` property value.

Question for @david-waltermire should we more clearly constrain the `help-text` value to only allow markdown-multiline or do you want to allow an alternate set of markdown syntax?

**Comment by david-waltermire** [comment]
> Per [ADR # 9](https://github.com/documents/adr/0009-constraint-based-help-docs.md), the following properties will be used in FedRAMP constraint definitions and must be recognized by the above capability:
> 
> * `//constraint/prop[@name='help-url'][@namespace='https://json.schemastore.org/sarif/2.1.0']`
> * `//constraint/prop[@name='help-text'][@namespace='https://json.schemastore.org/sarif/2.1.0']`
> * `//constraint/prop[@name='help-text-markdown'][@namespace='https://json.schemastore.org/sarif/2.1.0']`

Maybe change `help-text-markdown` to `help-markdown`, which is more consistent with SARIF.

> Question for [@david-waltermire](https://github.com/david-waltermire) should we more clearly constrain the `help-text-markdown` value to only allow metaschema markdown-multiline or do you want to allow an alternate set of markdown syntax?

We can using a constraint, but we may want to consider adding a `markdown-multiline` data type that is always markdown vs the current `markup-multiline` which is XHTML in XML and Markdown in JSON/YAML.

**Comment by david-waltermire** [comment]
In #139 I am using `https://docs.oasis-open.org/sarif/sarif/v2.1.0` as the namespace, which is more consistent with the actual SARIF namespace. Any concerns?

**Comment by aj-stein-gsa** [comment]
> Any concerns?

In https://github.com/GSA/fedramp-automation/pull/735 I used declared in the upstream Metaschema module you and I worked on.

https://github.com/metaschema-framework/metaschema-modules/blob/2f86aaf64b1628839f94761f832c3d3cc80f1f3a/sarif/sarif-module.xml#L8

Either way we should align it.

**Comment by brian-ruf** [comment]
@david-waltermire / @aj-stein-gsa on the namespace, I was only using was AJ indicated was used previously. As long as we are consistent, I don't have a strong feeling either way. 

It sounds like either requires some previous work to change. Please agree and advise. I'll align this issue as appropriate.

**Comment by brian-ruf** [comment]
@david-waltermire and @aj-stein-gsa apologies. Please ignore my previous comment. Upon looking more closely at both namespace values, I agree that `https://docs.oasis-open.org/sarif/sarif/v2.1.0` is more authoritative than `https://json.schemastore.org/sarif/2.1.0`. (I hadn't noticed the later was `schemastore.org`.)

With that and the field name change, I think we agree the three fields are:
- `//constraint/prop[@name='help-url'][@namespace='https://docs.oasis-open.org/sarif/sarif/v2.1.0']`
- `//constraint/prop[@name='help-text'][@namespace='https://docs.oasis-open.org/sarif/sarif/v2.1.0']`
- `//constraint/prop[@name='help-markdown'][@namespace='https://docs.oasis-open.org/sarif/sarif/v2.1.0']`

Also, I like the idea of defining and using a mardown-multiline data type when the content will always be markdown.

**Comment by aj-stein-gsa** [comment]
> @david-waltermire / @aj-stein-gsa on the namespace, I was only using was AJ indicated was used previously. As long as we are consistent, I don't have a strong feeling either way.
> 
> It sounds like either requires some previous work to change. Please agree and advise. I'll align this issue as appropriate.

Given the convo I propsed what Dave (and maybe me?) already considered the rightful namespace, it just wasn't correct in the module itself as came out here and some related PRs. So we agree on alignment, Dave will re-review https://github.com/metaschema-framework/metaschema-modules/pull/1 and we should be all set.
