### ISSUE TITLE
Function `substring-` functions are not implemented in Metapath processor

### ISSUE THREAD

**Issue by aj-stein-gsa** [metaschema-framework/metaschema-java#132]
### User Story

As a developer of Metaschema-based software, in order to write more efficient and easier to read Metapath in my models, I would like this library to implement the function `substring-after()`.

### Goals

- [x] Implement the `substring` class of functions for Metapath use:
  - [x] [`fn:substring`](https://www.w3.org/TR/xpath-functions-31/#func-substring): [#142](https://github.com/metaschema-framework/metaschema-java/pull/142)
  - [x] [`fn:substring-before`](https://www.w3.org/TR/xpath-functions-31/#func-substring-before): [#194](https://github.com/metaschema-framework/metaschema-java/pull/194)
  - [x] [`fn:substring-after`](https://www.w3.org/TR/xpath-functions-31/#func-substring-after): [#195](https://github.com/metaschema-framework/metaschema-java/pull/195)
- [x] Provide positive correct use of the function in unit tests
- [x] Provide incorrect correct negative use of the function unit tests

### Dependencies

N/A

### Acceptance Criteria

- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [x] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.
- ~All website and readme documentation affected by the changes in this issue have been updated.~

**Comment by david-waltermire** [comment]
Would it make sense to implement the following all at once?

- [ ] [fn:substring](https://www.w3.org/TR/xpath-functions-31/#func-substring)
- [ ] [fn:substring-before](https://www.w3.org/TR/xpath-functions-31/#func-substring-before)
- [ ] [fn:substring-after](https://www.w3.org/TR/xpath-functions-31/#func-substring-after)

I'd suggest skipping the collation variants of these functions. There is no support for collations yet and this would be a significant lift.

**Comment by aj-stein-gsa** [comment]
Sure I just wanted to do it this weekend or early next week to keep myself sharp. Adjust the issue?
