### ISSUE TITLE
Function `normalize-space()` is not implemented in Metapath processor

### ISSUE THREAD

**Issue by aj-stein-gsa** [metaschema-framework/metaschema-java#133]
### User Story

As a developer of Metaschema-based software, in order to write more efficient and easier to read Metapath in my models, I would like this library to implement the function `normalize-space()`.

### Goals

- [ ] Implement the function for Metapath use
- [ ] Provide positive correct use of the function in unit tests
- [ ] Provide incorrect correct negative use of the function unit tests

### Dependencies

N/A

### Acceptance Criteria

- [ ] All website and readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire** [comment]
This can be done as a follow on to #140 by providing a function that wraps the IStringItem.normalizeSpace() method.
