### ISSUE TITLE
Support custom constraint messages for non-expect constraints

### ISSUE THREAD

**Issue by david-waltermire** [metaschema-framework/metaschema-java#215]
### User Story

As a constraint author, I need support for the constraint messages that were added in https://github.com/metaschema-framework/metaschema/pull/40.

### Goals

Add support for custom messages in non-expect constraints.
- [~~`allowed-values`~~](https://pages.nist.gov/metaschema/specification/syntax/constraints/#allowed-values-constraints)
- [x] [`has-cardinality`](https://pages.nist.gov/metaschema/specification/syntax/constraints/#has-cardinality-constraints)
- [x] [`index`](https://pages.nist.gov/metaschema/specification/syntax/constraints/#index-constraints)
- [x] [`index-has-key`](https://pages.nist.gov/metaschema/specification/syntax/constraints/#index-has-key-constraints)
- [x] [`is-unique`](https://pages.nist.gov/metaschema/specification/syntax/constraints/#is-unique-constraints)
- [x] [`matches`](https://pages.nist.gov/metaschema/specification/syntax/constraints/#matches-constraints)
- [ ]  Create JUnit tests for each message implementation to verify support

### Dependencies

https://github.com/metaschema-framework/metaschema/pull/40

### Acceptance Criteria

- [ ] All website and readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
Is this where we discuss a notional `report` or `inform` element?

Suggesting `alert` as a possible alternative name?
