### ISSUE TITLE
Are conditional expressions that have test expressions without parentheses valid Metapath?

### ISSUE THREAD

**Issue by aj-stein-gsa** [metaschema-framework/metaschema-java#258]
### Describe the bug

Per previous discussion with the FedRAMP developer team, metaschema-java 2.2.0 (as released with `oscal-cli` 2.3.1) allows conditional Metapath expressions where the test expression after the `if` does not have parentheses. [According to my read of the spec](https://www.w3.org/TR/xpath-31/#id-conditionals), the EBNF specifies that behavior is non-conformant.

### Who is the bug affecting

Developers using conditonal logic for Metapath constraints' `test` attribute.

### How do we replicate this issue

Integration and/or unit tests TBD. For now, reveiw the following OSCAL-specific example in [the FedRAMP developer team's notes page in the wiki](https://github.com/GSA/fedramp-automation/wiki/Developer-Notes#test-expressions-for-conditionals-must-include-parentheses) with a simple constraint module with one constraint and a sample file.

The sample SSP:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<system-security-plan xmlns="http://csrc.nist.gov/ns/oscal/1.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/1.0 https://github.com/usnistgov/OSCAL/releases/download/v1.1.2/oscal_ssp_schema.xsd"
                      uuid="12345678-1234-4321-8765-123456789012">
  <metadata>
    <oscal-version>1.1.2</oscal-version>
  </metadata>
</system-security-plan>
```

Validation completes but with a constraint violation error with the document instance above (there are no library exceptions, evaluation completes).

```xml
<?xml version="1.0" encoding="UTF-8"?>
<metaschema-meta-constraints xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/metaschema/1.0 https://raw.githubusercontent.com/metaschema-framework/metaschema/refs/heads/develop/schema/xml/metaschema-meta-constraints.xsd">
    <context>
        <metapath target="/system-security-plan/metadata"/>
        <constraints>
            <expect id="oscal-version-required" target="oscal-version" test="if . = '1.1.2' then true() else false()" level="ERROR">
                <message>A FedRAMP document MUST have a valid version. DEBUG {.}</message>
            </expect>
        </constraints>
    </context>
</metaschema-meta-constraints>
```

The above constraint also, when violated, has a DEBUG value of 1.1.2, meaning the constraint _should not_ be violated.

The issue is resolved when the test expression properly uses parens.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<metaschema-meta-constraints xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/metaschema/1.0 https://raw.githubusercontent.com/metaschema-framework/metaschema/refs/heads/develop/schema/xml/metaschema-meta-constraints.xsd">
    <context>
        <metapath target="/system-security-plan/metadata"/>
        <constraints>
            <expect id="oscal-version-required" target="oscal-version" test="if (. = '1.1.2') then true() else false()" level="ERROR">
                <message>A FedRAMP document MUST have a valid version. DEBUG {.}</message>
            </expect>
        </constraints>
    </context>
</metaschema-meta-constraints>
```

### Expected behavior (i.e. solution)

When usng invalid test expression syntax, the Metaschema process in metaschema-java returns an exception indicating the syntax is invalid.

**Comment by david-waltermire** [comment]
Turns out this is caused here:

https://github.com/metaschema-framework/metaschema-java/blob/964b8456020ec810a0eb885208dda4584c660f9a/core/src/main/java/gov/nist/secauto/metaschema/core/metapath/MetapathExpression.java#L136

This is parsing the `expr` context, which doesn't have an EOF so it is doing a partial parse. According to:

https://github.com/metaschema-framework/metaschema-java/blob/964b8456020ec810a0eb885208dda4584c660f9a/core/src/main/antlr4/Metapath10.g4#L14

It should be parsing `metapath` instead which has the EOF.

https://github.com/metaschema-framework/metaschema-java/blob/964b8456020ec810a0eb885208dda4584c660f9a/core/src/main/antlr4/Metapath10.g4#L8

This one line change will fix the issue.
