### ISSUE TITLE
Unclear error message "The error was: stream is already consumed" for invalid Metapath expressions

### ISSUE THREAD

**Issue by aj-stein-gsa** [metaschema-framework/metaschema-java#289]
### User Story

As a developer of Metaschema-enabled tooling, in order to increase the speed of development and debugging Metapath code, I need more precise error messaging where I frequently receive the error message.

> "The error was: stream is already consumed"

A fairly complex example that I can to turn into a minimally viable and producible example is in [this GitHub Gist](https://gist.github.com/aj-stein-gsa/7f36c26b3fb2baec07892da23f02465d).

### Goals

- [ ] More precise explanation of the kind Metapath expression that cause the error and underlying exception
- [ ] More precision about the location in a module or external constraints file to identify which path in the module or constraint file is where the exception occurred (currently it only lists the constraint, not if it is the `test`, `target`, or `message`

### Acceptance Criteria

- [ ] All website and readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire** [comment]
I think this is caused by reusing a cached function result sequence that is stream (default) and not list backed. Streams cannot be reused, thus the need to ensure the sequence is list backed.

Based on my current theory, the following should fix the error. Change the code in `/metaschema-core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/impl/AbstractFunction.java` around line 254 to:
```java
        if (callingContext != null) {
          // ensure the result sequence is list backed
          result.getValue();
          // add result to cache
          dynamicContext.cacheResult(callingContext, result);
        }
```
