### ISSUE TITLE
string-join & contains

### ISSUE THREAD

**Issue by wandmagic** [metaschema-framework/metaschema-java#298]
### User Story

as a metapath user, string-join and contains would allow me to improve constraint quality downstream

### Goals

impliment string-join and contains

### Dependencies

unit tests

### Acceptance Criteria

- [ ] All website and readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by aj-stein-gsa** [comment]
Just a heads up: `contains` is already implemented and release, but maybe not `string-join` but need to check PRs. If the latter is coded, I do know it is not released yet, @wandmagic.

https://github.com/metaschema-framework/metaschema-java/blob/964b8456020ec810a0eb885208dda4584c660f9a/core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnContains.java#L27

**Comment by wandmagic** [comment]
thats great news! thanks for letting me know

**Comment by aj-stein-gsa** [comment]
On that note, it was a real pain to work around some bugs and the use of the bugfix operator in downstream usage of Metapath in FedRAMP OSCAL constraints, so I guess I pick this one up tonight after all. 😅
