### ISSUE TITLE
Diagram of models and/or instance

### ISSUE THREAD

**Issue by xee5ch** [metaschema-framework/metaschema-java#51]
# User Story:

As a Metaschema developer, in order to best understand how to mentally model or implement algorithms to process document instances conformant to Metaschema models, I would like functionality in the library to emit [Mermaid](https://mermaid.live) (be it Flow, Class, or Mindmap variant), [GraphViz](https://graphviz.org/), or other visualizations of the graph structures of a document or model in a format preferred by developers and users in the community.

## Goals:

Have the ability to visualize a document instance and its associated model to help understanding and development of Metaschema-aware tools.

## Dependencies:

N/A

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire** [comment]
I have the basic code working in #78 to generate a mermaid diagram for an arbitrary Metaschema module. A CLI command is still needed to instrument this API to fully address this issue.
